# Generated by Django 3.0.6 on 2020-05-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200515_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('redirectTo', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='categorianegocio',
            name='redirectTo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='panaderia',
            name='redirectTo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supermercado',
            name='redirectTo',
            field=models.CharField(max_length=200),
        ),
    ]
